import { createHash } from 'node:crypto';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { collectFragments } from '../src/lib/game/voiceCatalogue';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const texts = collectFragments();

const entries = texts.map((text) => ({
	id: createHash('sha1').update(text, 'utf8').digest('hex').slice(0, 10),
	text
}));

const byId = new Map<string, string>();
for (const { id, text } of entries) {
	const clash = byId.get(id);
	if (clash !== undefined && clash !== text) {
		throw new Error(`clip id collision ${id}: ${JSON.stringify(clash)} vs ${JSON.stringify(text)}`);
	}
	byId.set(id, text);
}

mkdirSync(resolve(root, 'voice'), { recursive: true });
writeFileSync(resolve(root, 'voice/lines.json'), JSON.stringify(entries, null, 2) + '\n');

const body = entries
	.map(({ id, text }) => `\t${JSON.stringify(text)}: ${JSON.stringify(id)}`)
	.join(',\n');
writeFileSync(
	resolve(root, 'src/lib/game/voice-map.ts'),
	`// AUTO-GENERATED by \`pnpm voice:lines\`. Do not edit by hand.\n` +
		`// Regenerate after changing spoken.ts or voiceCatalogue.ts.\n` +
		`export const voiceMap: Record<string, string> = {\n${body}\n};\n`
);

console.log(`voice:lines — ${entries.length} fragments → voice/lines.json, voice-map.ts`);
